name: bump-request
description: Create a pull request that bumps version.
inputs:
  command:
    description: Shell command for modifying files that contain versions such as package.json, Catgo.toml, etc.
    required: false
  github_token:
    description: GitHub access token.
    required: false
  release_type:
    description: How to bump the version. One of `major`, `minor`, `patch`.
    required: false
  version:
    description: You can also specify this directly instead of `release_type`.
    required: false
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: r7kamura/bump-request
        path: bump-request
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - run: deno run --allow-all bump-request/src/detectNextVersion.ts
      env:
        BUMP_REQUEST_INPUTS_RELEASE_TYPE: ${{ inputs.release_type }}
        BUMP_REQUEST_INPUTS_VERSION: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ inputs.github_token || github.token }}
      shell: bash
      id: detect_next_version
    - if: inputs.command
      run: |
        ${{ inputs.command }}
      env:
        VERSION: ${{ steps.detect_next_version.outputs.version }}
      shell: bash
    - if: ${{ !inputs.command }}
      run: deno run --allow-all bump-request/src/changeVersion.ts
      env:
        BUMP_REQUEST_VERSION: ${{ steps.detect_next_version.outputs.version }}
      shell: bash
    - run: deno run --allow-all bump-request/src/createPullRequest.ts
      env:
        BUMP_REQUEST_VERSION: ${{ steps.detect_next_version.outputs.version }}
        GITHUB_TOKEN: ${{ inputs.github_token || github.token }}
      shell: bash
branding:
  color: blue
  icon: git-pull-request
