name: bump-request
description: Create a pull request that bumps version.
inputs:
  command:
    description: Shell command for modifying files that contain versions such as package.json, Catgo.toml, etc.
    required: true
  github_token:
    description: GitHub access token.
    required: false
  version:
    description: Version to change to.
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - run: deno run --allow-all src/main.ts
      env:
        BUMP_REQUEST_INPUTS_COMMAND: ${{ inputs.command }}
        BUMP_REQUEST_INPUTS_VERSION: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ inputs.github_token || github.token }}
      shell: bash
branding:
  color: blue
  icon: git-pull-request
