name: bump-request
description: Create a pull request that bumps version.
inputs:
  command:
    description: Shell command for modifying files that contain versions such as package.json, Catgo.toml, etc.
    required: true
  github_token:
    description: GitHub access token.
    required: false
  version:
    description: Version to change to.
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Run command
      run: |
        ${{ inputs.command }}
      shell: bash
    - name: Create pull request
      run: |
        response=$(
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -f tag_name='v${{ inputs.version }}' \
            -f target_commitish='${{ github.ref }}' \
            /repos/${{ github.repository }}/releases/generate-notes
        )
        title=$(echo "${response}" | jq -r '.name')
        body=$(echo "${response}" | jq -r '.body')
        branch="bump-request-${GITHUB_RUN_ID}"
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git switch --create "${branch}"
        git add .
        git commit --message "Change version to ${{ inputs.version }}"
        git push --set-upstream origin "${branch}"
        gh pr create --body "${body}" --fill
      env:
        GITHUB_TOKEN: ${{ inputs.github_token || github.token }}
      shell: bash
branding:
  color: blue
  icon: git-pull-request
