name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r7kamura/setup-deno@problem-matchers
        with:
          deno-version: v1.x
      - run: deno fmt --check src/**/*.ts
      - run: deno lint src/**/*.ts
