name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: Tiryoh/gha-jobid-action@v1
        id: gha-jobid-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: lint
      - run: |
          echo ${{steps.gha-jobid-action.outputs.job_id}}
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/r7kamura/bump-request/check-runs/${{steps.gha-jobid-action.outputs.job_id}} \
            -f "output[title]=dummt title" -f "output[summary]=dummt summary"
        env:
          GH_TOKEN: ${{ github.token }}
